apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mdai-operator-secret-rollout
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/MyDecisive/example-argocd.git
    targetRevision: rlaw/mdai-labs-plus-envoy-hub-chart
    path: argocd/mdai/shared/operator-secret-rollout
  destination:
    name: in-cluster
    namespace: mdai
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - ServerSideApply=true
