apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: gateway
  namespace: mdai
spec:
  config:
    receivers:
      otlp/from_lb:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    processors:
      tail_sampling:
        decision_wait: 10s
        policies:
          - name: keep-all-the-errors
            type: and
            and:
              and_sub_policy:
                - name: error-sampling
                  type: status_code
                  status_code:
                    status_codes: [ERROR]
          - name: probabilistic-sample-high-volume-services
            type: and
            and:
              and_sub_policy:
                - name: high-volume-tail-sampling
                  type: string_attribute
                  string_attribute:
                    key: operation
                    values: ${env:HIGH_VOLUME_SERVICE_LIST}
                - name: probabilistic-policy
                  type: probabilistic
                  probabilistic:
                    sampling_percentage: 90
          - name: probabilistic-sample-medium-volume-services
            type: and
            and:
              and_sub_policy:
                - name: medium-volume-tail-sampling
                  type: string_attribute
                  string_attribute:
                    key: operation
                    values: ${env:MEDIUM_VOLUME_SERVICE_LIST}
                - name: probabilistic-policy
                  type: probabilistic
                  probabilistic:
                    sampling_percentage: 50
          - name: probabilistic-sample-low-volume-services
            type: and
            and:
              and_sub_policy:
                - name: low-volume-tail-sampling
                  type: string_attribute
                  string_attribute:
                    key: operation
                    values: ${env:LOW_VOLUME_SERVICE_LIST}
                - name: probabilistic-policy
                  type: probabilistic
                  probabilistic:
                    sampling_percentage: 10
          - name: always-sample-non-high-volume
            type: ottl_condition
            ottl_condition:
              error_mode: ignore
              span:
                - "attributes[\"operation\"] != \"high-volume-op\""
    exporters:
      debug/to_vendor: {}
    service:
      pipelines:
        logs/customer_pipeline:
          receivers: [otlp/from_lb]
          processors: [memory_limiter, tail_sampling, batch]
          exporters: [debug/to_vendor]

