apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loadbalancer-endpointslices-reader
  namespace: mdai
subjects:
  - kind: ServiceAccount
    name: loadbalancer
    namespace: mdai
roleRef:
  kind: Role
  name: loadbalancer-endpointslices-reader
  apiGroup: rbac.authorization.k8s.io
