apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    chart: cert-manager
    targetRevision: v1.19.1
    helm:
      parameters:
      - name: "crds.enabled"
        value: "true"
  destination:
    name: "in-cluster"
    namespace: cert-manager
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    retry:
      limit: 1