apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mdai-addon
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DecisiveAI/example-argocd.git
    targetRevision: ENG-941
    path: argocd/mdai/kustomize
  destination:
    name: "in-cluster"
    namespace: mdai
  syncPolicy:
    syncOptions:
    - PruneLast=true
    retry:
      limit: 4