
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}-dd-io-from
  namespace: {{ .Release.Namespace }}
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    processors:
      transform/promote_hostname:
        error_mode: ignore
        metric_statements:
          - context: datapoint
            statements:
              - set(resource.attributes["host.name"], attributes["host.name"]) where attributes["host.name"] != nil
              - delete_key(attributes, "host.name") where attributes["host.name"] != nil
    exporters:
      debug: {}
      datadog:
        api:
          key: "dummy-key"
          fail_on_invalid_key: false
        traces:
          endpoint: "http://envoy-proxy-xds-proxy.{{ .Release.Namespace }}.svc.cluster.local:8126"
        metrics:
          resource_attributes_as_tags: true
          endpoint: "http://envoy-proxy-xds-proxy.{{ .Release.Namespace }}.svc.cluster.local:8126"
        logs:
          endpoint: "http://envoy-proxy-xds-proxy.{{ .Release.Namespace }}.svc.cluster.local:8126"
    service:
      telemetry:
          resource:
            simulator: "{{ .Values.connection_name }}-from-collector"
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [datadog,debug]
        metrics:
          receivers: [otlp]
          processors: [transform/promote_hostname]
          exporters: [datadog,debug]
        logs:
          receivers: [otlp]
          exporters: [datadog,debug]