
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}-dd-io-from
  namespace: {{ .Release.Namespace }}
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    exporters:
      datadog:
        api:
          key: "dummy-key"
          fail_on_invalid_key: false
        traces:
          endpoint: "http://envoy-proxy.{{ .Release.Namespace }}.svc.cluster.local:8126"
        metrics:
          endpoint: "http://envoy-proxy.{{ .Release.Namespace }}.svc.cluster.local:8126"
        logs:
          endpoint: "http://envoy-proxy.{{ .Release.Namespace }}.svc.cluster.local:8126"
    service:
      telemetry:
          resource:
            simulator: "{{ .AppName }}-from-collector"
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [datadog]
        metrics:
          receivers: [otlp]
          exporters: [datadog]
        logs:
          receivers: [otlp]
          exporters: [datadog]