apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-otelgen-from
  namespace: {{ .Release.Namespace }}
  labels:
    app: otelgen-from
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelgen-from
  template:
    metadata:
      labels:
        app: otelgen-from
    spec:
      containers:
        # ---------------------------------------------------------
        # TRACES
        # ---------------------------------------------------------
        - name: otelgen-traces
          image: ghcr.io/krzko/otelgen:latest
          args:
            # Global Flags
            - "--insecure"
            - "--otel-exporter-otlp-endpoint"
            - "{{ .Release.Name }}-dd-io-from-collector.{{ .Release.Namespace }}.svc.cluster.local:4317"
            # Command & Subcommand
            - "traces"
            - "multi"
            # Command Flags (2 items/sec = ~120/min)
            - "--rate"
            - "2"

        # ---------------------------------------------------------
        # METRICS
        # ---------------------------------------------------------
        - name: otelgen-metrics
          image: ghcr.io/krzko/otelgen:latest
          args:
            # Global Flags
            - "--insecure"
            - "--otel-exporter-otlp-endpoint"
            - "{{ .Release.Name }}-dd-io-from-collector.{{ .Release.Namespace }}.svc.cluster.local:4317"
            # Command (Metrics does not require a subcommand)
            - "metrics"
            # Command Flags (2 items/sec = ~120/min)
            - "--rate"
            - "2"

        # ---------------------------------------------------------
        # LOGS
        # ---------------------------------------------------------
        - name: otelgen-logs
          image: ghcr.io/krzko/otelgen:latest
          args:
            # Global Flags
            - "--insecure"
            - "--otel-exporter-otlp-endpoint"
            - "{{ .Release.Name }}-dd-io-from-collector.{{ .Release.Namespace }}.svc.cluster.local:4317"
            # Command (Logs does not require a subcommand)
            - "logs"
            # Command Flags (2 items/sec = ~120/min)
            - "--rate"
            - "2"