apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-otelgen-from
  namespace: {{ .Release.Namespace }}
  labels:
    app: otelgen-from
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelgen-from
  template:
    metadata:
      labels:
        app: otelgen-from
    spec:
      containers:
        - name: otelgen-traces
          image: ghcr.io/krzko/otelgen:latest
          args:
            - "--insecure"
            - "--otel-exporter-otlp-endpoint"
            - "{{ .Release.Name }}-dd-io-from-collector.{{ .Release.Namespace }}.svc.cluster.local:4317"
            - "traces"
            - "multi"
            - "--rate"
            - "5"
            - "--duration"
            - "0"
        - name: otelgen-metrics
          image: ghcr.io/krzko/otelgen:latest
          args:
            - "--insecure"
            - "--otel-exporter-otlp-endpoint"
            - "{{ .Release.Name }}-dd-io-from-collector.{{ .Release.Namespace }}.svc.cluster.local:4317"
            - "metrics"
            - "--duration"
            - "0"
        - name: otelgen-logs
          image: ghcr.io/krzko/otelgen:latest
          args:
            - "--insecure"
            - "--otel-exporter-otlp-endpoint"
            - "{{ .Release.Name }}-dd-io-from-collector.{{ .Release.Namespace }}.svc.cluster.local:4317"
            - "logs"
            - "--duration"
            - "0"