apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-envoy
  labels:
    app: {{ .Release.Name }}-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-envoy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-envoy
      annotations:
        # This ensures the pod restarts if the ConfigMap changes
        checksum/config: {{ tpl (.Files.Get "files/envoy.yaml") . | sha256sum }}
    spec:
      containers:
        - name: envoy
          image: {{ .Values.envoy.image }}
          ports:
            - containerPort: {{ .Values.ingressPort }}
          volumeMounts:
            - name: envoy-config-volume
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
      volumes:
        - name: envoy-config-volume
          configMap:
            name: {{ .Release.Name }}-envoy-config