apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octant-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/mydecisive/charts/octant-ui
      chart: octant-ui
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/argocd/octant/values.yaml
    - repoURL: https://github.com/MyDecisive/example-argocd.git
      targetRevision: sp/octant-ui
      path: argocd/octant
      ref: values
  destination:
    name: "in-cluster"
    namespace: octant
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    retry:
      limit: 4
