apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../catalog/globals/base/mdaihub
- resources/mdaihub-params-configmap.yaml
replacements:
- source:
    kind: ConfigMap
    name: mdaihub-params
    fieldPath: data.HUB_NAME
  targets:
  - select:
      kind: MdaiHub
      name: mdaihub-template
    fieldPaths:
    - metadata.name
